# Generated by Django 5.1.6 on 2025-05-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_bio_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
